[build]
command = "next build"
publish = ".next"

[[plugins]]
package = "@netlify/plugin-nextjs"

[functions]
directory = "netlify/functions"
node_bundler = "esbuild"

[[redirects]]
from = "/api/versapay/*"
to = "/netlify/functions/:splat"
status = 200

[[redirects]]
from = "/api/versapay/checkout"
to = "/netlify/functions/checkout"
status = 200

[[redirects]]
from = "/api/versapay/ping"
to = "/netlify/functions/ping"
status = 200
