[build]
command = "next build"
publish = ".next"

[[plugins]]
package = "@netlify/plugin-nextjs"

[functions]
node_bundler = "esbuild"
external_node_modules = []
included_files = []

# Optional: local redirects for a clean API path
[[redirects]]
from = "/api/versapay/*"
to = "/.netlify/functions/versapay/:splat"
status = 200