[build]
command = "next build"
publish = ".next"

[[plugins]]
package = "@netlify/plugin-nextjs"

[functions]
directory = "netlify/functions"
node_bundler = "esbuild"

[[redirects]]
from = "/api/versapay/*"
to = "/.netlify/functions/:splat"
status = 200

[[headers]]
for = "/*"
[headers.values]
Content-Security-Policy = "frame-src 'self' https://ecommerce-api-uat.versapay.com https://ecommerce-api.versapay.com; child-src 'self' https://ecommerce-api-uat.versapay.com https://ecommerce-api.versapay.com; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://ecommerce-api-uat.versapay.com https://ecommerce-api.versapay.com"


